/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsFavoritesRouteImport } from './routes/bills.favorites'
import { Route as BillsAllRouteImport } from './routes/bills.all'

const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsFavoritesRoute = BillsFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => BillsRoute,
} as any)
const BillsAllRoute = BillsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => BillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRouteWithChildren
  '/bills/all': typeof BillsAllRoute
  '/bills/favorites': typeof BillsFavoritesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRouteWithChildren
  '/bills/all': typeof BillsAllRoute
  '/bills/favorites': typeof BillsFavoritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRouteWithChildren
  '/bills/all': typeof BillsAllRoute
  '/bills/favorites': typeof BillsFavoritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills' | '/bills/all' | '/bills/favorites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills' | '/bills/all' | '/bills/favorites'
  id: '__root__' | '/' | '/bills' | '/bills/all' | '/bills/favorites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/favorites': {
      id: '/bills/favorites'
      path: '/favorites'
      fullPath: '/bills/favorites'
      preLoaderRoute: typeof BillsFavoritesRouteImport
      parentRoute: typeof BillsRoute
    }
    '/bills/all': {
      id: '/bills/all'
      path: '/all'
      fullPath: '/bills/all'
      preLoaderRoute: typeof BillsAllRouteImport
      parentRoute: typeof BillsRoute
    }
  }
}

interface BillsRouteChildren {
  BillsAllRoute: typeof BillsAllRoute
  BillsFavoritesRoute: typeof BillsFavoritesRoute
}

const BillsRouteChildren: BillsRouteChildren = {
  BillsAllRoute: BillsAllRoute,
  BillsFavoritesRoute: BillsFavoritesRoute,
}

const BillsRouteWithChildren = BillsRoute._addFileChildren(BillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
